### ISSUE TITLE
Trying to run this on render.com

### ISSUE THREAD

**Issue by mr-wh1tehat** [randomu3/DALL-E-TGBot#2]
I used npm install as build command and npm start for run command in render's webservice. The deployment was successful, when using bot it always says
" Ваш запрос был отклонен из-за нашей системы безопасности. Ваше приглашение может содержать текст, который не разрешен нашей системой безопасности." I looked the logs on render.com and it says:
![Screenshot_20230312-024745_Bromite](https://user-images.githubusercontent.com/73610922/224512895-5039c5d1-be17-4c54-9609-873dbbb6914e.png)

Terminated by other GetUpdates Request: make sure that only one bot instance is running
Pls help

**Comment by randomu3** [comment]
Have you added an apiKey token?
{
  "openai": {
    "apiKey": "your-api-key"
  },
  "telegram": {
    "accessToken": "your-access-token"
  }
}

  
>Воскресенье, 12 марта 2023, 2:50 +05:00 от mr-wh1tehat ***@***.***>:
> 
> 
>I used npm install as build command and npm start for run command in render's webservice. The deployment was successful, when using bot it always says
>" Ваш запрос был отклонен из-за нашей системы безопасности. Ваше приглашение может содержать текст, который не разрешен нашей системой безопасности." I looked the logs on render.com and it says:
>Прервано другим запросом GetUpdates: убедитесь, что запущен только один экземпляр бота. 
>Пожалуйста, помогите.
>— 
>Ответьте на это письмо напрямую,  просмотрите его на GitHub или  отмените подписку . 
>Вы получаете это, потому что подписаны на эту тему. Идентификатор сообщения:  <randomu3/DALL-E-TGBot/issues/2  @  github  .  ком> 
 
 
С уважением,
magistrr fake
***@***.***

**Comment by mr-wh1tehat** [comment]
> Have you added an apiKey token? { "openai": { "apiKey": "your-api-key" }, "telegram": { "accessToken": "your-access-token" } }  
> Воскресенье, 12 марта 2023, 2:50 +05:00 от mr-wh1tehat ***@***.***>:     I used npm install as build command and npm start for run command in render's webservice. The deployment was successful, when using bot it always says " Ваш запрос был отклонен из-за нашей системы безопасности. Ваше приглашение может содержать текст, который не разрешен нашей системой безопасности." I looked the logs on render.com and it says: Прервано другим запросом GetUpdates: убедитесь, что запущен только один экземпляр бота. Пожалуйста, помогите. — Ответьте на это письмо напрямую, просмотрите его на GitHub или отмените подписку . Вы получаете это, потому что подписаны на эту тему. Идентификатор сообщения: <randomu3/DALL-E-TGBot/issues/2 @ github . ком>
>     С уважением, magistrr fake ***@***.***

Yes I added both openAI and telegram bot api key. Issue still persists. Btw, If openai key added on github repo, it gets revoked automatically. Maybe this is the issue.

**Comment by randomu3** [comment]
Maybe you published your repository and someone stole your token and is using it for their own purposes. Have you thought about that?

  
>Понедельник, 13 марта 2023, 20:54 +05:00 от mr-wh1tehat ***@***.***>:
> 
> 
>Have you added an apiKey token? { "openai": { "apiKey": "your-api-key" }, "telegram": { "accessToken": "your-access-token" } }  
>Воскресенье, 12 марта 2023, 2:50 +05:00 от mr-wh1tehat  @ . >:     I used npm install as build command and npm start for run command in render's webservice. The deployment was successful, when using bot it always says " Ваш запрос был отклонен из-за нашей системы безопасности. Ваше приглашение может содержать текст, который не разрешен нашей системой безопасности." I looked the logs on render.com and it says: Прервано другим запросом GetUpdates: убедитесь, что запущен только один экземпляр бота. Пожалуйста, помогите. — Ответьте на это письмо напрямую, просмотрите его на GitHub или отмените подписку . Вы получаете это, потому что подписаны на эту тему. Идентификатор сообщения: < /issues/2 @ github . ком>
>    С уважением, magistrr fake  @ .
Yes I added both openAI and telegram bot api key. Issue still persists. Btw, If openai key added on github repo, it gets revoked automatically. Maybe this is the issue.
—
Reply to this email directly,  view it on GitHub , or  unsubscribe .
You are receiving this because you commented. Message ID:  <randomu3/DALL-E-TGBot/issues/2/1466412652 @ github . com>  
 
С уважением,
magistrr fake
***@***.***

**Comment by mr-wh1tehat** [comment]
> Maybe you published your repository and someone stole your token and is using it for their own purposes. Have you thought about that?  
> Понедельник, 13 марта 2023, 20:54 +05:00 от mr-wh1tehat ***@***.***>:     Have you added an apiKey token? { "openai": { "apiKey": "your-api-key" }, "telegram": { "accessToken": "your-access-token" } }   Воскресенье, 12 марта 2023, 2:50 +05:00 от mr-wh1tehat @ . >:     I used npm install as build command and npm start for run command in render's webservice. The deployment was successful, when using bot it always says " Ваш запрос был отклонен из-за нашей системы безопасности. Ваше приглашение может содержать текст, который не разрешен нашей системой безопасности." I looked the logs on render.com and it says: Прервано другим запросом GetUpdates: убедитесь, что запущен только один экземпляр бота. Пожалуйста, помогите. — Ответьте на это письмо напрямую, просмотрите его на GitHub или отмените подписку . Вы получаете это, потому что подписаны на эту тему. Идентификатор сообщения: < /issues/2 @ github . ком>     С уважением, magistrr fake @ .
> Yes I added both openAI and telegram bot api key. Issue still persists. Btw, If openai key added on github repo, it gets revoked automatically. Maybe this is the issue. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: <randomu3/DALL-E-TGBot/issues/2/1466412652 @ github . com>     С уважением, magistrr fake ***@***.***

Yes ofcourse. The problem is, If I paste the OPENAI key on github repository as environment variable or whatever, it gets reported as stolen and openai will revoke my api key. So the code should be updated to get ai key as env variable from deployment server i guess
